[package]
name = "cow-mug"
version = "0.0.1"
authors = ["edubrunaldi <eduardo.brunaldi.santos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
